In [20]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
from PIL import Image
import numpy as np

In [25]:
# Load the Iris dataset
iris = datasets.load_iris()
#For image preview
feature_data = iris.data[:, 0]
min_value, max_value = feature_data.min(), feature_data.max()
normalized_data = 255 * (feature_data - min_value) / (max_value - min_value)
normalized_data = normalized_data.astype(np.uint8)
image_shape = (10, 15)  
image_data = normalized_data.reshape(image_shape)

image = Image.fromarray(i)
image.show()


In [7]:


X = iris.data  # Features
y = iris.target  # Target labels
print(X.shape)
print(y.shape)

# Split the dataset into a training set and a test set (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier on the training data
rf_classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred = rf_classifier.predict(X_test)
print(y_pred)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
matrix=confusion_matrix(y_test,y_pred)
print(matrix)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Display a classification report
report = classification_report(y_test, y_pred, target_names=iris.target_names)
print("Classification Report:\n", report)

(150, 4)
(150,)
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy: 100.00%
Classification Report:
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

